name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: ["main"]         # deploy whenever you push to main
  workflow_dispatch:           # allow manual runs from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true        # ← IMPORTANT if your theme is a git submodule

      # Go is required when using Hugo Modules
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.148.0"  # match your local version if different
          extended: true

      # Optional: vendor modules for reproducible builds (safe to keep)
      - name: Hugo mod vendor
        run: hugo mod vendor

      - name: Build
        env:
          HUGO_ENV: production
        run: hugo --minify --gc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
